### ISSUE TITLE
管理画面の作成

### ISSUE THREAD

**Issue by masa-rock** [pyonkichi369/kamachat#5]
# 概要
* 管理画面を作成する

# やること
* dbを作成して、tweetするもの、しないものを選別できるようにする。
* chatgptで生成した文章を編集できるようにする。
* 自身で投稿したいものを入力できるようにする。

**Comment by pyonkichi369** [comment]
マルチ認証はすでに実装してあって管理画面はあるのから以下issueで対応していただければと！
https://github.com/pyonkichi369/kamachat/issues/1

**Comment by pyonkichi369** [comment]
ここの内容マージしたのでクローズするね！
https://github.com/pyonkichi369/kamachat/issues/1
